### ISSUE TITLE
Burp 2020.2爆错

### ISSUE THREAD

**Issue by PolarPeak** [ggg4566/BurpBountyPlus#1]
java.lang.NullPointerException
	at burp.e0h.b(Unknown Source)
	at burp.aa8.getHttpService(Unknown Source)
	at burp.g4o.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.ar7.a(Unknown Source)
	at burp.ds3.a(Unknown Source)
	at burp.ds3.a(Unknown Source)
	at burp.g6s.b(Unknown Source)
	at burp.aqe.a(Unknown Source)
	at burp.ds3.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
	at javax.swing.JTabbedPane.add(JTabbedPane.java:835)
	at burpbounty.Tags$1.run(Tags.java:95)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at burp.e0h.b(Unknown Source)
	at burp.aa8.getHttpService(Unknown Source)
	at burp.g4o.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.ar7.a(Unknown Source)
	at burp.ds3.a(Unknown Source)
	at burp.ds3.a(Unknown Source)
	at burp.g6s.b(Unknown Source)
	at burp.aqe.a(Unknown Source)
	at burp.ds3.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
	at javax.swing.JTabbedPane.add(JTabbedPane.java:835)
	at burpbounty.Tags$1.run(Tags.java:95)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
![image](https://user-images.githubusercontent.com/44831329/126030050-c3d48ed8-bc7f-4525-9ac4-ae3f71b2e80b.png)
![image](https://user-images.githubusercontent.com/44831329/126030057-dfbe0d35-efa1-47a0-a4d3-e9faffddbe17.png)

**Comment by ggg4566** [comment]
这个错误是和key的HaE 那个信息标记插件一起加载出现的问题，不影响使用
