### ISSUE TITLE
burp  2022.8.1报错

### ISSUE THREAD

**Issue by aa506** [ggg4566/BurpBountyPlus#6]
加载时错误代码

java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.ib_.d(Unknown Source)
	at burp.dxb.getHttpService(Unknown Source)
	at burp.dxt.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.h0d.a(Unknown Source)
	at burp.bbc.a(Unknown Source)
	at burp.f2k.a(Unknown Source)
	at burp.f2k.a(Unknown Source)
	at burp.hrn.a(Unknown Source)
	at burp.xq.b(Unknown Source)
	at burp.g4k.b(Unknown Source)
	at burp.hrn.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.hrr.c(Unknown Source)
	at burp.hrr.b(Unknown Source)
	at burp.hrr.a(Unknown Source)
	at burp.hrr.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.ib_.d(Unknown Source)
	at burp.dxb.getHttpService(Unknown Source)
	at burp.dxt.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.h0d.a(Unknown Source)
	at burp.bbc.a(Unknown Source)
	at burp.f2k.a(Unknown Source)
	at burp.f2k.a(Unknown Source)
	at burp.hrn.a(Unknown Source)
	at burp.xq.b(Unknown Source)
	at burp.g4k.b(Unknown Source)
	at burp.hrn.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.hrr.c(Unknown Source)
	at burp.hrr.b(Unknown Source)
	at burp.hrr.a(Unknown Source)
	at burp.hrr.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ggg4566** [comment]
@sodmelody 看报错信息好像不是本插件的问题呢，我这边加载都没问题呢，是不是看错了？

**Comment by est6633** [comment]
师傅你解决了嘛 这个问题
